protoc -I=. --python_out=. hetcons.proto
protoc -I=. --python_out=. common.proto
protoc -I=. --python_out=. charlotte.proto
protoc -I=. --python_out=. vegvisirCommon.proto
protoc -I=. --python_out=. sendall.proto
protoc -I=. --python_out=. vector.proto
protoc -I=. --python_out=. vegvisir.proto
protoc -I=. --python_out=. generic.proto
protoc -I=. --python_out=. frontier.proto
protoc -I=. --python_out=. handshake.proto
protoc -I=. --python_out=. vegvisirNetwork.proto
